### ISSUE TITLE
API not returning results

### ISSUE THREAD

**Issue by jspingau** [tdurieux/leboncoin-api#53]
Hi,

Since yesterday the API does not return any results on previously working queries. When debugging from lib/search.js I see the content returned by the search API only contains content like:

`{"url":"https://c.datado.me/captcha/?initialCid=AHrlqAAAAAMAfhnhHfj6eVIAMw89Zw==&hash=05B30BD9055986BD2EE8F5A199D973&t=fe"}`

so it looks like some captcha validation is expected ...from an API call, weird.

**Comment by tdurieux** [comment]
Apparently, they put new security in place. It does not sound good for this library :/

**Comment by alexismoreau** [comment]
I use this library for the category 'ventes_immobilieres' and everything seems to be working fine

**Comment by tdurieux** [comment]
@jspingau are you using a server, if yes from which provider?
@alexismoreau same question

Thank you

**Comment by jspingau** [comment]
@tdurieux: I am, Scaleway.

**Comment by alexismoreau** [comment]
I use it both on my OVH VPS and from my local computer to check just now. 
No problem at all.

**Comment by alexismoreau** [comment]
Maybe you are blacklisted, how many request do you make ?
Did you try on a local computer ?

**Comment by jspingau** [comment]
yes, might be what happened. I'll check running on a local computer later today and keep everyone updated.

**Comment by jspingau** [comment]
ok, I could finally test sooner than expected.

I confirm it works locally so I was blacklisted.

This is weird because usage should not be that high: this is a script that creates rss feeds out of searches on lbc. Granted, the rss reader does fetch the subscriptions on a regular basis but I'm the only one using this, so volume must be a few hundred hits per day...

Maybe using a different API key will help. I cannot find the documentation of api.leboncoin.fr, anyone knows how to get an API key?

Otherwise, I guess I'll just setup a vanilla proxy on a separate VM and change it as I'm being blacklisted..

**Comment by jspingau** [comment]
closing the issue as it has nothing to do with the library. Thanks for your help!

**Comment by tdurieux** [comment]
> Maybe using a different API key will help. I cannot find the documentation of api.leboncoin.fr, anyone knows how to get an API key?

It is impossible to get, it is not a public API.

**Comment by jspingau** [comment]
Hi,

For what it's worth: I finally got a chance to setup a new host (changing the IP was a no-no in my case for various reasons). I confirm only my IP was banned and not Scaleway in NL overall :-)

I'll keep updating this thread in case I get blacklisted again.

cheers,

**Comment by Skymirrh** [comment]
I am also getting similar responses to requests from a script running once every twice or three days with something like 20-30 requests (depending on the number of pages to scrape since the previous time).

Strangely, it does not seem that LBC bans the IP, as it is still working when sending the requests from a browser on the same computer. I am currently checking if adding request headers by copying them from browser to script is working.

**Comment by alexismoreau** [comment]
how do you send the requests from the browser ?

**Comment by Skymirrh** [comment]
> how do you send the requests from the browser ?

From the `Developer Tools`, under `Network` tab. You can craft custom requests from there.

Or, an easier option in our case: just go to LBC and start a search for something: results will appear. At this point, open `Developer Tools` under `Network` tab, then click on the `Search` button directly from the results page: you will see a new request to the API pop up in `Network` tab, which looks like what this lib.

**Comment by Skymirrh** [comment]
I can confirm that adding the following three headers has solved the issue, albeit it might be temporary:
```
"User-Agent": "BOUYAKA",
"Accept-Language": "artiche",
"Accept-Encoding": "please do me all the needful",
```
As you can see, the actual values for these headers does not really matter, it seems just having them present is enough to fool the API.

I will make a PR with more acceptable values.

**Comment by Skymirrh** [comment]
Apparently the changes in #56 are not enough to fix the issue for @alexismoreau. Perhaps there is more to be discovered? Can we reverse engineer their API blocking strategy? :P

Can you try on your production environment by using actual headers from a browser as suggested in my comment above? See if there's something that works if you actually try to be treated as a regular browser. If it still does not work even with the exact same headers as a browser, is the response still the same or is it something else?

Note: when trying to reproduce the same headers as your browser, do not forget to use a value of `*` or `identity` for `Accept-Encoding` rather than using your browser's values (`gzip`, `deflate`, etc.) otherwise the API will send you responses in a compressed format.

**Comment by alexismoreau** [comment]
Will try everything you suggested tonight or tomorrow. I'll keep you updated

**Comment by alexismoreau** [comment]
I tried with : 
`
{
      method: 'POST',
      hostname: 'api.leboncoin.fr',
      port: null,
      path: '/finder/search',
      headers: {
        origin: 'https://www.leboncoin.fr',
        api_key: 'ba0c2dad52b3ec',
        'content-type': 'text/plain;charset=UTF-8',
        accept: '*/*',
        referer: 'https://www.leboncoin.fr/annonces/offres/ile_de_france/',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6',
        'Accept-Encoding': '*',
      }
`
the response is still :
`{ url: 'https://c.datado.me/captcha/?initialCid=AHrlqAAAAAMAYdImbmdv7eAAM0sdRg==&hash=05B30BD9055986BD2EE8F5A199D973&t=fe' }`

Maybe I'm really blacklisted

**Comment by Skymirrh** [comment]
> We also need to add 'User-Agent', 'Accept-Language' & 'Accept-Encoding' to item.js

Nice catch, hadn't seen that. It seems there are two requests in `item.js` (one for details and the other for phone number), and fun fact, the second one already has two additional headers:
https://github.com/tdurieux/leboncoin-api/blob/5280d9ae90e48f1fc9e7f94f4708dd8e9756512a/lib/item.js#L116-L117

**Comment by tdurieux** [comment]
Hi all,

@alexismoreau your IP is probably blacklisted for the moment, you should answer the captcha several times and theoretically it should work again on your server.

@Skymirrh can you add the header for the requests that are missing it? Thanks a lot

**Comment by jspingau** [comment]
Hello everyone,

My new server got blacklisted again after a few days so I went ahead and
added:

 "User-Agent": "Gecko",
>  "Accept-Language": "en-US,en;q=0.8,fr;q=0.6",
>  "Accept-Encoding": "*",


In the header sections of both search.js and item.js and did the trick,
Thanks!

It looks like DataDome is pretty sensitive to "Accept-Encoding": "*" . When
trying more real life variations of Accept-Encoding (text/html, text/plain,
application/json) I got denied every single time, use any sort of junk,
including application\json it works... go figure.

I'll continue monitoring and keep you updated during the next few days.

Cheers,

**Comment by tdurieux** [comment]
Looking at DataDome, it will be difficult to maintain a reliable service using nodejs. 
Especially if the technique that this library will use it public. 

I am not sure that this library makes sense anymore.

**Comment by Skymirrh** [comment]
I am just discovering DataDome right now. Perhaps a solution would be to contact LBC and see if they can allow the use of a bot provided we respect their terms, e.g. throttling requests, using a specific user-agent, not allowing pages with more than the default size of 35.

**Comment by apetitjean** [comment]
In my opinion it doesn't really matter given the fact that scraping LBC is not permitted in the site's general utilization conditions. 
Hence if we don't hide we are a bot we will be blocked.

**Comment by jspingau** [comment]
Hi, I see my server got blacklisted again just after a few hours applying
the headers trick... others having the problem confirm this?

**Comment by Skymirrh** [comment]
@apetitjean Thanks for the excerpt.

Fun tidbit, which means basically everybody linking to LBC from anywhere is already breaking the TOS:

> Aucun lien hypertexte ne peut être créé vers le Service LEBONCOIN sans l'accord préalable et exprès de LBC France.

**Comment by alexismoreau** [comment]
same as @jspingau , I changed my production server to change my ip, got it working for 100 requests but now I got blocked again on item getDetails API.

**Comment by Skymirrh** [comment]
I've played a bit with the LBC API, fiddling with the headers and requests salvos timings to see how I could fool DataDome.

What I've found so far:
- DataDome expects a well-formed request with propers headers, and notably those from this list:
```
Host: api.leboncoin.fr
User-Agent: {a well-formed browser user-agent}
Accept-Language: {any}
Accept-Encoding: {any}
Referer: https://www.leboncoin.fr/
Origin: https://www.leboncoin.fr
Cookie: {datadome cookie}
```
- DataDome surveils the amount/frequency of requests done with the same "set" of headers.
- And also surveils the amount/frequency of requests done with different sets but from the same IP.
- If you go over the threshold, you will be greeted with the following page when trying to access LBC:
![firefox_2019-08-20_22-38-02](https://user-images.githubusercontent.com/4659919/63382989-43201000-c39c-11e9-8d07-412d85da1069.png)

I suspect this page is triggered by having an API response matching the links above in this thread: `https://c.datado.me/captcha/?initialCid={bla bla}`. As you can see from the screenshot above, they have a form where you can provide an email to request authorization for bots. It sends you a mail with the following message:
> DataDome is missioned by Leboncoin to protects its websites and API against unwanted bot traffic for security and performance concerns. 
>
> To do this, we identify bots by analyzing hundreds of attributes and matching them to our knowledge base and/or statistical patterns. 
>
> Unidentified bots are automatically categorised by DataDome's algorithms as "bad bots". It seems to be your case since you have been blocked on Leboncoin. 
>
> If you wish to regain access, the first step is to authenticate your robot by filling-in the form. After validation, it will be moved from the "bad bot" to the "commercial bot" family and this will give you the opportunity to be whitelisted by the website owner.

Along with a link to this form: https://docs.google.com/forms/d/e/1FAIpQLSenPmi8P-6jAZDq_DeFuXOHCj91J-62d56NhX_YC3JLePBcnw/viewform

I have filled the form with data identifying my personal bot (with a custom user-agent and my own address mail as contact mail). I will keep you up to date as to what they answer.

In the meantime, if you wish not to get blocked by DataDome, here's how to fool it (at least temporarily):
- Make sure your headers are formatted properly (notably with a valid browser user-agent and datadome cookie).
- Do not change page limit (keep it at 35 like the website), throttle your requests (I suggest something like one every 30s) and add random scattering (±10s) to make your requests look like a regular user using the search function page-per-page.
- If you run multiple queries sequentially, randomize the order every time your run the sequence.

**Comment by tdurieux** [comment]
@Skymirrh Thanks for your feedback!

**Comment by tdurieux** [comment]
I just pushed a refactoring of the requests. Now all requests use the same header and share the DataDom cookies. 
It should be a little bit more reliable.

**Comment by tdurieux** [comment]
Hello all,

Do my last changes "fix" the problem?

Thomas

**Comment by jspingau** [comment]
Hello Thomas,

Thanks for the patch. Jury's still out in my case: It mostly works, but it
looks like I'm being blacklisted again for a few hours and then it works
again.

Pretty odd situation overall so I'm still monitoring what's going on: It
was working on Thursday, blacklisted again on Thursday night through
Friday. Saturday and today it worked again...

I'll keep you posted at the end of the week with more solid info.

cheers

**Comment by Skymirrh** [comment]
> Do my last changes "fix" the problem?

No change w.r.t. the observations in my last comment: proper headers allow to fool DataDome for a while, but only if you behave "like a human".

Sending too many requests too fast too regularly and with an identical pattern still gets you blocked. You have to make sure the API calls look like a user browsing the website. On my end, the strategies proposed above are working fine:
- Make sure to use the same page limit as the actual website (for now: 35).
- Throttle requests to about 1 per 30 seconds and scatter them with a random factor (±10s).
- When scraping multiple queries, randomize the order of queries. For each query, if scraping multiple pages: get the pages sequentially from 1 to {target page}.
- If the script runs on a schedule (e.g. once every day), add a random factor to the schedule (e.g. ±1h).

I have not been blocked since implementing these; I suspect this is enough to fool DataDome's bot detection in my case (non-intensive use).

**Comment by ronyrun** [comment]
thanks @Skymirrh 

I tried every tricks you listed. But it's working erratically.
I'm not even able to access the https://c.datado.me/captcha/?************* url to try to answer the captcha....

I make 3 calls every 4 to 5 minutes....
I guess My IP is blacklisted, even swith throttling, and randoming calls etc.. etc.....

**Comment by Skymirrh** [comment]
Is your bot running 24/7? Because for example I don't think making 3 calls every 4 to 5 minutes BUT 24/7 qualifies as "looking like a human browsing LBC" :D

**Comment by ronyrun** [comment]
Is your bot running 24/7? 
NO, not from 10PM  to 6AM

I tried to register my bot into Datadome (for personal / not professional use).
I don't know if it's a good point.

Currently it's still not working...

**Comment by jspingau** [comment]
As promised, short update on this issue after 10 days of usage. It was a bit hit or miss a for a few days since my last message, but since then my server has not been blacklisted. Overall, still pretty weird situation. My guess is that the datadome configuration was altered for a few days and then reverted back...

Anyone experiencing being blacklisted again recently?

**Comment by alexismoreau** [comment]
@Skymirrh have you got any news from Datadome / LBC ?

**Comment by Skymirrh** [comment]
@alexismoreau Nope. No answer whatsoever.

**Comment by a-farsi** [comment]
Hi everybody, 
I got a 403 http error when I try to access the api. Is there any authentication step that I didn't validate before?
Thanks in advance

**Comment by tdurieux** [comment]
Not really, it is leboncoin blocking the requests.
You need to create an infrastructure that leboncoin will be not able to detect.

**Comment by a-farsi** [comment]
Hi tdurieux, 
Thanks for your answer.
the set of api aren't public?
Do you have more details about any kind of infrastructure that leboncoin doesn't block?
Thanks in advance
